import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(x=>x[1]);
let checks=0;
function harness(){
  const elements=new Map(ids.map(id=>[id,{value:'',checked:false,hidden:false,disabled:false,textContent:'',innerHTML:'',duration:NaN,currentTime:0,querySelectorAll:()=>[],play:async()=>{},files:[]}]));
  const storage=new Map(), requests=[];
  let server=async()=>({ok:true,rows:[]});
  const context=vm.createContext({document:{getElementById:id=>{assert.ok(elements.has(id),'Missing element '+id);return elements.get(id);},querySelectorAll:()=>[]},localStorage:{setItem:(k,v)=>storage.set(k,v),getItem:k=>storage.get(k)||null,removeItem:k=>storage.delete(k)},URL,URLSearchParams,console,confirm:()=>true,fetch:async(url,options={})=>{requests.push({url,options});const data=await server(url,options);return {ok:data.ok!==false,json:async()=>data};}});
  vm.runInContext(source,context);const evaluate=code=>vm.runInContext(code,context);
  elements.get('adminKey').value='secret';elements.get('malId').value='21';elements.get('episodeOffset').value='51';
  return {elements,storage,requests,evaluate,server:fn=>server=fn,click:id=>elements.get(id).onclick()};
}
async function check(name,fn){await fn();checks++;console.log('PASS',name);}
await check('timestamp inputs accept seconds, mm:ss and hh:mm:ss; reject malformed values',()=>{const h=harness();assert.equal(h.evaluate("seconds('01:30.5')"),90.5);assert.equal(h.evaluate("seconds('1:02:03')"),3723);assert.equal(h.evaluate("seconds('0')"),0);assert.throws(()=>h.evaluate("seconds('1:99')"));assert.throws(()=>h.evaluate("seconds('abc')"));});
await check('manual ranges reject empty/partial and video-overrun values',()=>{const h=harness();assert.throws(()=>h.evaluate('manualPatch()'));h.elements.get('opStart').value='0';assert.throws(()=>h.evaluate('manualPatch()'));h.elements.get('opEnd').value='90';h.elements.get('video').duration=60;assert.throws(()=>h.evaluate('manualPatch()'));});
await check('not-present controls disable time fields',()=>{const h=harness();h.elements.get('opAbsent').checked=true;h.elements.get('opAbsent').onchange();assert.equal(h.elements.get('opStart').disabled,true);assert.equal(h.evaluate('manualPatch().opAbsent'),true);});
await check('bulk mapping, checkpoints and retry-failed-only work without saving during preview',async()=>{const h=harness();let round=0;h.elements.get('bulkStart').value='1';h.elements.get('bulkEnd').value='2';h.elements.get('bulkMediaIds').value='ABC123\nDEF456';h.server(async(url,options)=>{const b=JSON.parse(options.body);assert.equal(b.mode,'prepare');return {ok:true,rows:b.items.map((r,i)=>({...r,expected:null,patch:{op:{start:0,end:90}},after:{op:{start:0,end:90}},status:round===0&&i===1?'failed':'ready',error:round===0&&i===1?'rate limited':undefined}))};});await h.click('bulkPreview');assert.equal(h.evaluate('rows[0].episode'),52);assert.equal(h.evaluate('rows[1].episode'),53);assert.equal(h.evaluate('rows[1].status'),'failed');assert.equal(h.requests.length,1);const draft=JSON.parse(h.storage.get('skip-studio-import'));assert.equal(draft.malId,21);assert.ok(!JSON.stringify(draft).includes('secret'));round++;await h.click('retry');const retry=JSON.parse(h.requests[1].options.body);assert.equal(retry.items.length,1);assert.equal(retry.items[0].episode,53);assert.equal(h.evaluate('rows[1].status'),'ready');assert.equal(h.evaluate('rows[1].error'),undefined);});
await check('resume reads a saved draft and fetches pending records only',async()=>{const h=harness();h.storage.set('skip-studio-import',JSON.stringify({version:1,malId:21,rows:[{episode:1,status:'saved'},{episode:2,mediaId:'ABC123',status:'pending'}]}));h.server(async(url,options)=>{const b=JSON.parse(options.body);assert.equal(b.items.length,1);assert.equal(b.items[0].episode,2);return {ok:true,rows:[{episode:2,status:'ready',expected:null,patch:{op:{start:0,end:90}},after:{op:{start:0,end:90}}}]};});await h.click('resume');assert.equal(h.evaluate('rows[0].status'),'saved');assert.equal(h.evaluate('rows[1].status'),'ready');});
await check('save submits only selected records and retains successful state',async()=>{const h=harness();h.elements.get('manual').hidden=true;h.evaluate("importMalId=21;rows=[{episode:1,selected:true,status:'ready',expected:null,patch:{op:{start:0,end:90}}},{episode:2,selected:false,status:'ready'}]");h.server(async(url,options)=>{const b=JSON.parse(options.body);assert.equal(b.mode,'apply');assert.equal(b.items.length,1);assert.equal(b.items[0].episode,1);return {ok:true,count:1,commit:'abc123456789'};});await h.click('saveSelected');assert.equal(h.evaluate('rows[0].status'),'saved');assert.equal(h.evaluate('rows[1].status'),'ready');assert.equal(h.evaluate('saving'),false);});
await check('failed save preserves preview for a safe retry',async()=>{const h=harness();h.evaluate("importMalId=21;rows=[{episode:1,selected:true,status:'ready',expected:null,patch:{op:{start:0,end:90}}}]");h.server(async()=>{throw Error('Network error');});await h.click('saveSelected');assert.equal(h.evaluate('rows[0].status'),'ready');assert.ok(h.elements.get('saveStatus').textContent.includes('preview is retained'));assert.equal(h.elements.get('saveSelected').disabled,false);});
await check('pause ends after current batch and leaves remaining episodes resumable',async()=>{const h=harness();h.evaluate("importMalId=21;rows=Array.from({length:8},(_,i)=>({episode:i+1,mediaId:'ABC123',status:'pending'}))");h.server(async(url,options)=>{h.elements.get('pause').onclick();return {ok:true,rows:JSON.parse(options.body).items.map(r=>({...r,status:'ready',expected:null,patch:{op:{start:0,end:90}},after:{op:{start:0,end:90}}}))};});await h.evaluate('runPreview()');assert.equal(h.requests.length,1);assert.equal(h.evaluate("rows.filter(r=>r.status==='pending').length"),2);});
await check('player adjustment and use-current-time preserve subsecond precision',()=>{const h=harness();h.elements.get('adjustField').value='opStart';h.elements.get('opStart').value='01:30';h.elements.get('plus').onclick();assert.equal(h.elements.get('opStart').value,90.5);h.elements.get('video').duration=100;h.elements.get('video').currentTime=12.3456;h.elements.get('useTime').onclick();assert.equal(h.elements.get('opStart').value,12.346);});
console.log(`OK: ${checks} UI behavior checks passed.`);
